_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": darwin-arm64
learning_rate:
    value: 0.13939937816145853
max_depth:
    value: 3
n_estimators:
    value: 492
